# itk-version: 3.0.0
version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  leantime:
    image: leantime/leantime:latest
    networks:
      - app
      - frontend
    env_file:
      - ./.env
      - ./.env.local
    ports:
      - '8080'
    volumes:
      - ./userfiles:/var/www/html/userfiles:rw
      # Volume to store public files, logo etc
      - ./public_userfiles:/var/www/html/public/userfiles:rw
    extra_hosts:
      # Unknown why this is needed. Container won't connect otherwise
      - host.docker.internal:host-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
